FROM openjdk:8-jdk-alpine
ENV HOME=/app
ARG PORT=8081
ENV PORT=$PORT
ADD ./target/*.jar ${HOME}/app.jar
ADD ./scripts/docker-entrypoint.sh ${HOME}/docker-entrypoint.sh
WORKDIR ${HOME}
EXPOSE ${PORT}/tcp
EXPOSE 8000/tcp
ENTRYPOINT sh ./docker-entrypoint.sh